name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macOS-11.0
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install rsync
      - run: mkdir -p dist
      - run: curl -L https://github.com/danramteke/leaf-press/releases/download/0.4.17/leaf-press-macos-11.0.tgz | tar xzf -
      - run: ./leaf-press build
