name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          apt-get update && apt-get install -y rsync curl
          cd /usr/local/bin
          curl -L https://github.com/danramteke/leaf-press/releases/download/0.4.15/leaf-press-ubuntu-20.04.tgz | tar xzf - 
          cd -
          leaf-press build 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist